version: '3'

vars:
  SLIDES_SOURCE: presentations
  OUTPUT_DIR: public
  LEGACY_SOURCE: legacy
  DEFAULT_PORT: 8000

tasks:
  default:
    desc: Show available tasks (default)
    cmds:
      - task --list

  build:
    desc: Build the entire website
    cmds:
      - ./build.sh

  serve:
    desc: Serve website or presentation with auto-reload
    summary: |
      Serve the entire website or a specific presentation with auto-reload.

      Usage: task serve [presentation-name]
      Examples:
        task serve              # Serve entire website
        task serve git-101      # Serve specific presentation
    cmds:
      - ./serve.sh {{.CLI_ARGS}}

  clean:
    desc: Clean the output directory
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - echo "✅ Cleaned {{.OUTPUT_DIR}}"

  new:
    desc: Create a new presentation from template
    summary: |
      Create a new presentation from the template.

      Usage: task new <presentation-name>
      Example: task new my-talk
    cmds:
      - ./new.sh {{.CLI_ARGS}}

  list:
    desc: List all presentations
    silent: true
    cmds:
      - uvx --with pyyaml python scripts/list_presentations.py {{.SLIDES_SOURCE}} {{.LEGACY_SOURCE}}
